sudo: false
language: python
python: 
  - "3.5"
env:
  global:
    # Pinned to a commit on the master branch
    - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/d20d4d2e3ade40e4daf6424bccab71bd79a38607"
install: 
  - "pip install -r requirements_test.txt"
  - curl -s -S --retry 3 $BASEDIR/tests/install.sh | bash -
script:
  - "./open-contracting_standard-maintenance-scripts_tests_script.sh"
  - "py.test"
